import React, { useEffect, useState } from 'react';
import {  motion, easeOut } from 'framer-motion';
import { Quote, Star } from 'lucide-react';
import axios from 'axios';
import { serverURL } from '@/constants';
import { Skeleton } from '@/components/ui/skeleton';

interface Testimonial {
  name: string;
  role: string;
  content: string;
  avatar?: string;
}



const Testimonials = () => {
  const [testimonials, setTestimonials] = useState<Testimonial[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchTestimonials = async () => {
      try {
        const response = await axios.get(`${serverURL}/api/testimonials`);
        if (response.data && response.data.length > 0) {
          setTestimonials(response.data);
        } else {
          setTestimonials([
            { name: "Sarah Johnson", role: "Product Manager", content: "This AI platform has completely changed how I learn new technical skills. The course generation is incredibly accurate and insightful." },
            { name: "David Chen", role: "Technical Lead", content: "The quality of courses generated by this AI is astounding. It's like having a personal tutor available 24/7." },
            { name: "Emma Williams", role: "Student", content: "Finally, a learning platform that understands my pace. AI Teacher Chat is a game-changer for complex topics." },
            { name: "Michael Brown", role: "Entrepreneur", content: "Speed and quality are unmatched. I've built three complete training modules for my team in just one afternoon." }
          ]);
        }
      } catch (error) {
        console.error("Error fetching testimonials:", error);
        setTestimonials([
          { name: "Sarah Johnson", role: "Product Manager", content: "This AI platform has completely changed how I learn new technical skills. The course generation is incredibly accurate and insightful." },
          { name: "David Chen", role: "Technical Lead", content: "The quality of courses generated by this AI is astounding. It's like having a personal tutor available 24/7." },
          { name: "Emma Williams", role: "Student", content: "Finally, a learning platform that understands my pace. AI Teacher Chat is a game-changer for complex topics." },
          { name: "Michael Brown", role: "Entrepreneur", content: "Speed and quality are unmatched. I've built three complete training modules for my team in just one afternoon." }
        ]);
      } finally {
        setIsLoading(false);
      }
    };

    fetchTestimonials();
  }, []);

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  // const itemVariants = {
  //   hidden: { opacity: 0, scale: 0.95, y: 20 },
  //   visible: {
  //     opacity: 1,
  //     scale: 1,
  //     y: 0,
  //     transition: {
  //       duration: 0.5,
  //       ease: "easeOut"
  //     }
  //   }
  // };
  const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.5,
      ease: easeOut,
    },
  },
};


  if (isLoading) {
    return (
      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-6 md:px-10">
          <div className="grid md:grid-cols-2 gap-8">
            {[1, 2, 3, 4].map((i) => (
              <Skeleton key={i} className="h-64 rounded-3xl" />
            ))}
          </div>
        </div>
      </section>
    );
  }

  return (
    <section id="testimonials" className="py-24 md:py-32 bg-slate-50 relative overflow-hidden">
      <div className="max-w-7xl mx-auto px-6 md:px-10 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-20"
        >
          <span className="text-primary font-bold tracking-widest uppercase text-sm mb-4 block">Testimonials</span>
          <h2 className="text-3xl md:text-5xl font-bold mb-6 text-slate-900 leading-tight">
            Trusted by Learners <br className="hidden md:block" /> Around the Globe
          </h2>
          <div className="h-1.5 w-24 bg-primary mx-auto rounded-full" />
        </motion.div>

        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          className="grid md:grid-cols-2 gap-10"
        >
          {testimonials.map((testimonial, index) => (
            <motion.div
              key={index}
              variants={itemVariants}
              whileHover={{ y: -5 }}
              className="bg-white p-10 rounded-[40px] shadow-sm hover:shadow-2xl transition-all duration-300 relative border border-slate-100"
            >
              <Quote className="absolute top-10 right-10 h-12 w-12 text-primary/10" />

              <div className="flex gap-1 mb-6">
                {[1, 2, 3, 4, 5].map((s) => (
                  <Star key={s} className="h-4 w-4 fill-primary text-primary" />
                ))}
              </div>

              <p className="text-slate-600 italic text-xl leading-relaxed mb-8">
                "{testimonial.content}"
              </p>

              <div className="flex items-center gap-4">
                <div className="h-14 w-14 rounded-full bg-primary/10 flex items-center justify-center font-bold text-primary text-xl">
                  {testimonial.name.charAt(0)}
                </div>
                <div>
                  <h4 className="font-bold text-lg text-slate-900">{testimonial.name}</h4>
                  <p className="text-primary text-sm font-semibold">{testimonial.role}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default Testimonials;
