import {
  Award,
  BarChart,
  Brain,
  BookOpen,
  Clock,
  FileText,
  Globe,
  Headphones,
  Layers,
  MessageSquare,
  Target,
  Video,
   Zap,        
  Briefcase,  
  Calendar,      
  CheckSquare 
} from 'lucide-react';

export const PRICING_FEATURES = [
  'Sub-Topic Limit',
  'Access Duration',
  'Theory & Image Course',
  'Create Courses',
  'AI Teacher Chat',
  'Course in 23+ Languages',
   'Calendar Scheduler',
  'Todo Center',
  'Video & Theory Course',
  'Resume Builder',
  'AI Notebook',
  'Interview Preparation',
  'Certification',
  'Priority Support',
  'Advanced Analytics',
  
   'Skill Booster',
] as const;
import { LucideIcon } from 'lucide-react';

export const PRICING_FEATURE_ICONS: Record<string, LucideIcon> = {
  'Sub-Topic Limit': Layers,
  'Access Duration': Clock,
  'Theory & Image Course': BookOpen,
  'Create Courses': FileText,
  'AI Teacher Chat': MessageSquare,
  'Course in 23+ Languages': Globe,
  'Video & Theory Course': Video,
  'Calendar Scheduler': Calendar,
  'Todo Center': CheckSquare,
  'Resume Builder': FileText,
  'AI Notebook': Brain,
  'Interview Preparation': Target,
  'Certification': Award,
  'Priority Support': Headphones,
  'Advanced Analytics': BarChart,
  'Skill Booster': Zap,
};

export const PRICING_PLAN_FEATURES: Record<string, Record<string, boolean | string>> = {
  free: {
    'Sub-Topic Limit': '5 per course',
    'Access Duration': '7 days',
    'Theory & Image Course': true,
    'Create Courses': '1 course only',
    'AI Teacher Chat': true,
    'Course in 23+ Languages': false,
    'Video & Theory Course': false,
    'Calendar Scheduler': true,
    'Todo Center': true,
    'Resume Builder': false,
    'AI Notebook': false,
    'Interview Preparation': false,
    'Certification': false,
    'Priority Support': true,
    'Advanced Analytics': false,
     'Skill Booster': false,
  },
  monthly: {
    'Sub-Topic Limit': '10 per course',
    'Access Duration': '1 month',
    'Theory & Image Course': true,
    'Create Courses': '20 courses only',
    'AI Teacher Chat': true,
    'Course in 23+ Languages': false,
    'Video & Theory Course': true,
    'Calendar Scheduler': true,
    'Todo Center': true,
    'Resume Builder': true,
    'AI Notebook': true,
    'Interview Preparation': true,
    'Certification': true,
    'Priority Support': true,
    'Advanced Analytics': true,
    'Skill Booster': false,
  },
  yearly: {
    'Sub-Topic Limit': '10 per course',
    'Access Duration': '1 year',
    'Theory & Image Course': true,
    'Create Courses': 'Unlimited',
    'AI Teacher Chat': true,
    'Course in 23+ Languages': true,
    'Video & Theory Course': true,
    'Calendar Scheduler': true,
'Todo Center': true,
    'Resume Builder': true,
    'AI Notebook': true,
    'Interview Preparation': true,
    'Certification': true,
    'Priority Support': true,
    'Advanced Analytics': true,
     'Skill Booster': true,
  },
};

export const PRICING_PLAN_ORDER: Record<string, number> = {
  free: 0,
  monthly: 1,
  yearly: 2,
};
